from attr import attrs, attrib

@attrs(kw_only=True)
class FileRequest:
    created_at             = attrib(default=None)
    created_by_email       = attrib(default=None)
    created_by_name        = attrib(default=None)
    expiration             = attrib(default=None)
    expired                = attrib(default=False)
    folder_id              = attrib(default=None)
    folder_name            = attrib(default=None)
    id                     = attrib(default=None)
    link                   = attrib(default=False)
    link_url               = attrib(default=None)
    message                = attrib(default=None)
    metadata               = attrib(default={})
    name                   = attrib(default=None)
    notify_all_recipients  = attrib(default=False)
    notify_uploader        = attrib(default=None)
    require_email          = attrib(default=False)
    subject                = attrib(default=None)
    template_name          = attrib(default=None)
    user_id                = attrib(default=None)
    uuid                   = attrib(default=None)
